# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: '@hsuanyukuo'
email: hsuanyukuo63@gmial.com
description: > # this means to ignore newlines until "baseurl:"
url: "http://hykuo.net" # the base hostname & protocol for your site
github_username:  hy-kuo
timezone:         Asia/Taiwan
google_analytics: UA-39592718-2
# Build settings
markdown: kramdown
